fixed ssh and hotpluggable eth0

diff --git a/meta-hydrogreen/recipes-core/telemetry-init/files/telemetry b/meta-hydrogreen/recipes-core/telemetry-init/files/telemetry
--- a/meta-hydrogreen/recipes-core/telemetry-init/files/telemetry
+++ b/meta-hydrogreen/recipes-core/telemetry-init/files/telemetry
@@ -21,6 +21,18 @@ start() {
         exit 1
     fi
 
+    TIMEOUT=4
+    echo "Waiting for LORA to be ready..."
+    while [ ! -e "/dev/ttyS0" ] && [ $TIMEOUT -gt 0 ]; do
+        sleep 1
+        TIMEOUT=$((TIMEOUT - 1))
+    done
+
+    if [ ! -e "/dev/ttyS0" ]; then
+        echo "Error: LORA not found. Exiting."
+        exit 1
+    fi
+
     $DAEMON_PATH >> /var/log/telemetry.log 2>&1 &
 
     echo $! > "$PIDFILE"
